### ISSUE TITLE
Scope value in "Auth" tab gets cleared after Generate Token

### ISSUE THREAD

**Issue by cmenzi** [EsperoTech/yaade#212]
When we define a variable in Environments (e.g. `SCOPES` = `api://dbf86d30-1ec4-4abe-b8e8-e6ef62145b83/.default`) and use it in the "Auth" tab via `${SCOPES}` and then click "Generate Token", after success token generation, the "SCOPE" value gets cleared and is not remembered anymore.

Expected:
The `Scope` value in the "Auth" tab stays after "Generate Token"

**Comment by jonrosner** [comment]
Thanks for reporting this. Is it only the scopes value or any field in the auth tab?

**Comment by cmenzi** [comment]
Hi @jonrosner 

It's only the "Scope" value in the "Auth" tab.

## Before "Generate Token"
![image](https://github.com/user-attachments/assets/30902d19-a3f4-4157-b6e2-ab365bb9a039)

## After "Generate Token"

![image](https://github.com/user-attachments/assets/447270ce-021f-49cc-90e9-0250cb035abc)

**Comment by jonrosner** [comment]
This is fixed in the newest nightly release

**Comment by cmenzi** [comment]
Still don't work

**Comment by jonrosner** [comment]
I pushed another fix for this. Please check out the nightly container and see if your problem is resolved.

**Comment by cmenzi** [comment]
Nope. Still gets cleared after pressing "Generate Token". When I then press F5, it gets correctly loaded.

**Comment by jonrosner** [comment]
Please check if you are running the correct nightly image: do `docker images` and check the `IMAGE ID`. It should be `1cd1a89f1ae1`.

I tried it both locally and remotely, in collections and requests auth and I cannot reproduce this anymore.

**Comment by cmenzi** [comment]
![image](https://github.com/user-attachments/assets/c9b0a90c-f933-4adc-8535-a22ec9b19591)

https://github.com/user-attachments/assets/de9c11c1-2b29-4e5c-ac8c-31ecc5d8db4c

**Comment by jonrosner** [comment]
Thanks for the video! I was looking in the wrong place the whole time. I pushed yet another fix to nightly. Hope this resolves the issue finally.

**Comment by cmenzi** [comment]
https://github.com/user-attachments/assets/35d2a02c-d4d2-4ee6-a595-5a0041b597ee

We are approaching it, ... :-)

**Comment by cmenzi** [comment]
Ok, was just caching issue. Had to "hard-reload" the app in the browser. Now, it finally works!

🎉

**Comment by jonrosner** [comment]
Glad to hear :+1:
